
var Names = {
  ACCOUNT_SETTINGS: 'Account Settings',
  ACTIVE: 'Active',
  ADD: 'Add',
  ADD_NEW_POST: '',
  ADD_NEW_PRE: 'Add New',
  ADMIN: 'Administrator',
  ADMINISTRATOR: 'Administrator',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  ANALYTICS: 'Analytics',
  APPROVED: 'Approved',
  BASIC_USER_INFO: 'Basic User Information',
  BLOCKED: 'Blocked',
  BLOCKED_USER: 'Blocked User',
  BT_ADD: 'Add',
  BT_ADD_NEW: 'Add New',
  BT_BLOCK: 'Block',
  BT_CANCEL: 'Cancel',
  BT_CLEAR: 'Clear',
  BT_CLOSE: 'Close',
  BT_DELETE: 'Delete',
  BT_DISABLE: 'Disable',
  BT_ENABLE: 'Enable',
  BT_LOGIN: 'Login',
  BT_LOGOUT: 'Logout',
  BT_REGISTER: 'Register',
  BT_SAVE: 'Save',
  BT_SORT: 'Sort',
  BT_UNBLOCK: 'Unblock',
  BT_UPLOAD: 'Upload',
  BT_VERIFY: 'Verify',
  CHANGE_PASSWORD: 'Change password',
  CHANGE_PROFILE_PICTURE: 'Add/ Change profile picture',
  CHANGE_USER_INFO: 'Change name, username, and date of birth',
  CHANGE_USER_PREFERENCES: 'Change user preferences',
  CONFIRM: 'Please Confirm',
  CONFIRM_AUTHORIZE: 'Are you sure you want to authorize this?',
  CONFIRM_DELETE: 'Are you sure you want to delete this?',
  CONFIRM_SAVE: 'Are you sure you want to save this?',
  CONFIRM_UPDATE: 'Are you sure you want to update this?',
  CURRENT_PASSWORD: 'Current Password',
  DATE_OF_BIRTH: 'Date of Birth',
  DISABLED: 'Disabled',
  DISABLED_USER: 'Disabled User',
  DISCOUNT: 'Discount',
  EMAIL: 'Email Address',
  ENTER_ABOVE_TEXT: 'Enter above text',
  EXPIRED: 'Expired',
  FEMALE: 'Female',
  FINALIZATION: 'Finalization',
  INACTIVE: 'Inactive',
  INITIALIZATION: 'Initialization',
  INVALID: 'Invalid',
  IS_NEW_USER: 'New user?',
  LOGIN: 'Please Login',
  MALE: 'Male',
  MSG_ACCOUNT_BLOCKED: 'Your account is temporarily blocked',
  MSG_ACCOUNT_DISABLED: 'Your account is disabled',
  MSG_ACCOUNT_UNVERIFIED: 'Your account has not yet been verified by admin',
  MSG_ALREADY_DELETED: 'It has been already deleted',
  MSG_BARCODE_EXISTS: 'Entered barcode already exists',
  MSG_CANNOT_UNDO: 'This cannot be undone.',
  MSG_CODE_EXISTS: 'Entered code already exists',
  MSG_DELETE_SUCCESS: 'Successfully deleted',
  MSG_EMAIL_EXISTS: 'Entered email address already exists',
  MSG_ENTER_PASSWORD: 'Enter your password',
  MSG_ERROR_OCCURRED: 'An error occurred',
  MSG_FILL_ALL: 'Please fill all the fields',
  MSG_IN_USE: 'Cannot delete. It\'s in use.',
  MSG_INCORRECT_PRE_PASSWORD: 'Current password is incorrect',
  MSG_INVALID_DATE: 'Entered date is invalid',
  MSG_NAME_EXISTS: 'Entered name already exists',
  MSG_NO_USER: 'Entered username does not exist',
  MSG_NOT_LOGGED_IN: 'You are not logged in',
  MSG_ONLY_JPG: 'Only JPG images are supported',
  MSG_PASSWORD_INCORRECT: 'Entered password is incorrect',
  MSG_PASSWORD_MISMATCH: 'Passwords mismatch',
  MSG_SAVE_SUCCESS: 'Successfully saved',
  MSG_SESSION_EXPIRED: 'Your session has been expired. Please login again.',
  MSG_TELEPHONE_EXISTS: 'Entered telephone number already exists',
  MSG_UNKNOWN_ERROR: 'Unknown error occurred ',
  MSG_UPDATE_SUCCESS: 'Successfully updated',
  MSG_UPLOAD_SUCCESS: 'Successfully uploaded',
  MSG_USERNAME_EXISTS: 'Username already exists',
  MY_ACCOUNT: 'My Account',
  NAME: 'Name',
  NAV_ACCOUNT: 'Account',
  NAV_HOME: 'Home',
  NAV_LOGOUT: 'Logout',
  NEUTRAL: 'Neutral',
  NEW: 'New',
  NEW_PASSWORD: 'New Password',
  NEW_USER: 'New User',
  NEXT_PAGE: 'Next Page',
  NIC: 'NIC/ Passport',
  NO: 'No',
  ONLY: 'Only',
  PASSWORD: 'Password',
  PREVIOUS_PAGE: 'Previous Page',
  PROFILE: 'Profile',
  PROFILE_PICTURE: 'Profile Picture',
  REGISTER: 'New User Registration',
  REGISTERED_ON: 'Registered On',
  REJECTED: 'Rejected',
  REPEAT_PASSWORD: 'Repeat Password',
  RESET: 'Reset',
  ROWS_PER_PAGE: 'Rows per page',
  SEARCH: 'Search',
  SECURITY_INFO: 'Security Information',
  SELECTED: 'selected',
  SEX: 'Sex',
  SYSTEM_LOG: 'System Log',
  TELEPHONE: 'Telephone No.',
  UNKNOWN: 'Unknown',
  USER: 'User',
  USER_ACCOUNTS: 'User Accounts',
  USER_PREFERENCES: 'User Preferences',
  USER_PRIVILEGES: 'User Privileges',
  USER_STATE: 'User Status',
  USER_TYPE: 'User Type',
  USERNAME: 'Username',
  VALID: 'Valid',
  VALIDITY: 'Validity',
  VERIFIED: 'Verified',
  VERIFIED_USER: 'Verified User',
  YES: 'Yes',
  MORE_INFO: 'More Info',
  TYPE: 'Type',
  ID: 'ID',
  DONE: 'Done',
  CLOSE: 'Close',
  SELECT: 'Select',
  ALL_CATEGORIES: 'All Categories'
}

export default Names
